<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Anatta.Framework</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ManagedBass" Version="4.0.2" />
      <PackageReference Include="ManagedBass.Fx" Version="4.0.2" />
      <PackageReference Include="OpenTK" Version="4.9.4" />
      <PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
      <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
      <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*" />
    </ItemGroup>
    <ItemGroup>
      <None Update="bass.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
